/* A C++ Programme to find define the Example of Numerical Analysis Problems */
#include<iostream.h>
#include<conio.h>
void main()
{
	int x, y, n, i;
	float upper, lower, height, temp, final;
	printf("\n Input the value of n : ");
	scanf("%d", &n);
	for(i=lower; i<=upper; i = i+height)
	{
		scanf("%d", & x[i]);
		scanf("%d", & y[i]);
		for(i = lower+height; i<=upper+height; i = i+height)
		{
			temp = 2*y[i];
		}
		final = (height/2)*(lower+upper+temp);
		printf("\n The Final Result : ");
	}
}