// A C++ Programme to swap the values of two integers
#include<iostream.h>
#include<conio.h>
void swap(int x, int y, int a, int b)
{
	x == a;
	cout<<"\n X == "<<a;
	y == b;
	cout<<"\n Y == "<<b;
	cout<<"\n After Swapping the values ";
	cout<<"\n ========================= ";
	x == b;
	cout<<"\n X == "<<b;
	y == a;
	cout<<"\n Y == "<<a;
}
void main()
{
	int x, y, a, b;
	clrscr();
	cout<<"\n Enter The Values of A and B : ";
	cin>>a>>b;
	swap(x, y, a, b);
	getch();
}d
